'use strict';

const MARKET_BUY_REQUEST_EVENT = 'market-buy-request';
const MARKET_BUY_RESPONSE_EVENT = 'market-buy-response';
const MARKET_BUY_FAILURE_REASONS = {
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  PLAYER_NOT_REGISTERED: 'PLAYER_NOT_REGISTERED',
  CHARACTER_NOT_FOUND: 'CHARACTER_NOT_FOUND',
  MARKET_NOT_FOUND: 'MARKET_NOT_FOUND',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_NOT_TRADEABLE: 'ITEM_NOT_TRADEABLE',
  INVALID_DIRECTION: 'INVALID_DIRECTION',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  INSUFFICIENT_MARKET_STOCK: 'INSUFFICIENT_MARKET_STOCK',
  NO_SHIP_AVAILABLE: 'NO_SHIP_AVAILABLE',
  PARTIAL_WRITE_REVERSED: 'PARTIAL_WRITE_REVERSED',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
};

module.exports = {
  MARKET_BUY_REQUEST_EVENT,
  MARKET_BUY_RESPONSE_EVENT,
  MARKET_BUY_FAILURE_REASONS,
};
