'use strict';

const MARKET_SELL_REQUEST_EVENT = 'market-sell-request';
const MARKET_SELL_RESPONSE_EVENT = 'market-sell-response';
const MARKET_SELL_FAILURE_REASONS = {
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  PLAYER_NOT_REGISTERED: 'PLAYER_NOT_REGISTERED',
  CHARACTER_NOT_FOUND: 'CHARACTER_NOT_FOUND',
  MARKET_NOT_FOUND: 'MARKET_NOT_FOUND',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_NOT_TRADEABLE: 'ITEM_NOT_TRADEABLE',
  INVALID_DIRECTION: 'INVALID_DIRECTION',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  INSUFFICIENT_ITEM_QUANTITY: 'INSUFFICIENT_ITEM_QUANTITY',
  MARKET_DOES_NOT_BUY_ITEM: 'MARKET_DOES_NOT_BUY_ITEM',
  PARTIAL_WRITE_REVERSED: 'PARTIAL_WRITE_REVERSED',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED'
};

module.exports = {
  MARKET_SELL_REQUEST_EVENT,
  MARKET_SELL_RESPONSE_EVENT,
  MARKET_SELL_FAILURE_REASONS
};
