'use strict';

const MARKET_QUOTE_REQUEST_EVENT = 'market-quote-request';
const MARKET_QUOTE_RESPONSE_EVENT = 'market-quote-response';
const MARKET_QUOTE_FAILURE_REASONS = {
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  PLAYER_NOT_REGISTERED: 'PLAYER_NOT_REGISTERED',
  CHARACTER_NOT_FOUND: 'CHARACTER_NOT_FOUND',
  MARKET_NOT_FOUND: 'MARKET_NOT_FOUND',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_NOT_TRADEABLE: 'ITEM_NOT_TRADEABLE',
  INVALID_DIRECTION: 'INVALID_DIRECTION',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  MARKET_DOES_NOT_BUY_ITEM: 'MARKET_DOES_NOT_BUY_ITEM',
};

module.exports = {
  MARKET_QUOTE_REQUEST_EVENT,
  MARKET_QUOTE_RESPONSE_EVENT,
  MARKET_QUOTE_FAILURE_REASONS,
};
